#!/usr/bin/env php
<?php

declare(strict_types=1);

use PmConverter\Handler;
const EOL = PHP_EOL;
const DS = DIRECTORY_SEPARATOR;

const PM_VERSION = '1.7';

$paths = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../autoload.php',
    __DIR__ . '/vendor/autoload.php'
];
$file = null;
foreach ($paths as $path) {
    if (file_exists($path)) {
        require_once $file = $path;
        break;
    }
}

is_null($file) && throw new RuntimeException('Unable to locate autoload.php file.');

$handler = new Handler();
$handler::printVersion();
$handler::printCopyright();
try {
    $handler->init($argv);
    $handler->start();
} catch (Exception $e) {
    fwrite(STDERR, sprintf('ERROR: %s%s', $e->getMessage(), EOL));
    exit(1);
}
